const $=s=>document.querySelector(s),fresh=()=>({index:0,selected:null,score:0,streak:0,wrongChain:0,health:100,spo2:98,pulse:72,focus:100,answered:false,review:[],records:[],symptoms:[],anatomyEpisodes:[],affectedRegions:[]}),state=fresh();
const el={conditionText:$("#conditionText"),conditionDetail:$("#conditionDetail"),spo2:$("#spo2"),pulse:$("#pulse"),focus:$("#focus"),healthValue:$("#healthValue"),healthBar:$("#healthBar"),caseNumber:$("#caseNumber"),caseTotal:$("#caseTotal"),progressBar:$("#progressBar"),category:$("#category"),type:$("#type"),difficulty:$("#difficulty"),streak:$("#streak"),sourceBadge:$("#sourceBadge"),scenario:$("#scenario"),question:$("#question"),choices:$("#choices"),feedback:$("#feedback"),feedbackIcon:$("#feedbackIcon"),feedbackLabel:$("#feedbackLabel"),feedbackTitle:$("#feedbackTitle"),feedbackText:$("#feedbackText"),consequence:$("#consequence"),choiceNotes:$("#choiceNotes"),detailBox:$("#detailBox"),submit:$("#submitButton"),next:$("#nextButton"),modal:$("#resultModal"),avatarStage:$("#avatarStage"),avatarState:$("#avatarState"),avatarCallout:$("#avatarCallout"),symptomChips:$("#symptomChips"),recordLog:$("#recordLog"),recordCount:$("#recordCount")};
let soundOn=false,audioContext=null,fullBank=[...QUESTION_BANK];
function tone(freq,duration,type="sine",delay=0){if(!soundOn)return;audioContext??=new(window.AudioContext||window.webkitAudioContext)();let o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.12,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+duration)}
function sound(kind){if(kind==="ok"){tone(520,.15);tone(720,.2,"sine",.12)}else if(kind==="wrong"){tone(180,.35,"sawtooth");tone(120,.45,"sawtooth",.18)}else{tone(260,.15,"square");tone(220,.15,"square",.22);tone(180,.8,"sawtooth",.44)}}
function shuffle(list){for(let i=list.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function render(){let q=QUESTION_BANK[state.index];state.selected=null;state.answered=false;document.body.className="";el.caseNumber.textContent=String(state.index+1).padStart(2,"0");el.caseTotal.textContent=`/ ${QUESTION_BANK.length}`;el.progressBar.style.width=`${(state.index+1)/QUESTION_BANK.length*100}%`;el.category.textContent=q.category;el.type.textContent=q.questionType;el.difficulty.textContent=q.acceptedAnswerSets[0].length>1?`${q.acceptedAnswerSets[0].length}つ選択`:"1つ選択";el.sourceBadge.textContent=q.source;el.scenario.textContent=q.scenario;el.question.textContent=q.question;el.choices.innerHTML="";q.choices.forEach((c,i)=>{let b=document.createElement("button");b.className="choice";b.innerHTML=`<span class="choice-index">${i+1}</span><span>${escapeQuestionText(c)}</span>`;b.onclick=()=>select(i);el.choices.appendChild(b)});el.feedback.className="feedback";el.detailBox.open=false;el.submit.hidden=false;el.submit.disabled=true;el.next.hidden=true;status();avatar(null)}
function select(i){let q=QUESTION_BANK[state.index];if(state.answered||i<0||i>=q.choices.length)return;if(q.acceptedAnswerSets[0].length>1){let selected=selectionIndices(state.selected);selected=selected.includes(i)?selected.filter(n=>n!==i):[...selected,i];state.selected=selected.length?selected:null}else state.selected=i;[...el.choices.children].forEach((b,n)=>{const selected=selectionIndices(state.selected).includes(n);b.classList.toggle("selected",selected);b.setAttribute("aria-pressed",String(selected))});el.submit.disabled=!canSubmitAnswer(q,state.selected)}
function mistakeLimit(){return Math.max(1,Math.ceil(QUESTION_BANK.length/5))}
function mistakeLimitReached(){return state.review.length>=mistakeLimit()}
function submit(){if(!canSubmitAnswer(QUESTION_BANK[state.index],state.selected)||state.answered)return;state.answered=true;let q=QUESTION_BANK[state.index],ok=isCorrectAnswer(q,state.selected),e=q.effect,damage=0;el.sourceBadge.textContent=q.source;[...el.choices.children].forEach((b,i)=>{b.disabled=true;if(isCorrectOption(q,i))b.classList.add("correct");if(selectionIndices(state.selected).includes(i)&&!ok)b.classList.add("wrong")});if(ok){state.score++;state.streak++;state.wrongChain=0;let heal=0;state.health=Math.min(100,state.health+heal);state.focus=Math.min(100,state.focus+4);el.feedback.className="feedback show correct-feedback";el.feedbackIcon.textContent="✓";el.feedbackLabel.textContent="CORRECT ASSESSMENT";el.feedbackTitle.textContent="判断は適切です";el.consequence.textContent="患者の状態を捉え、新たな投影を防いだ。"}else{state.streak=0;state.wrongChain++;state.review.push(q.id);let previousHealth=state.health;state.health=Math.max(0,Math.round(100*(1-state.review.length/mistakeLimit())));damage=previousHealth-state.health;state.focus=Math.max(5,state.focus-5);if(e.disease){state.symptoms.push(e.name);state.anatomyEpisodes.push({questionId:q.id,...e})}document.body.className=e.className;el.feedback.className="feedback show";el.feedbackIcon.textContent="!";el.feedbackLabel.textContent="REVIEW";el.feedbackTitle.textContent="判断を振り返りましょう";el.consequence.textContent=`ミス ${state.review.length} / ${mistakeLimit()}回｜正答と解説を確認しましょう。`;if(e.disease){el.conditionText.textContent=e.name;el.conditionDetail.textContent=e.detail}}state.records.unshift({caseNo:state.index+1,quote:formatSelection(q,state.selected),ok,result:ok?"適切な判断。":e.disease?`${e.name}を体験。復習リストに追加しました。`:"患者との境界が揺らいだ。復習リストに追加しました。"});records();avatar(ok?null:e);el.feedbackText.textContent=`正答：${formatCorrectAnswers(q)}。${q.explanation}`;el.choiceNotes.innerHTML=q.notes.map((n,i)=>`<article class="choice-rationale ${isCorrectOption(q,i)?"is-correct":"is-wrong"}"><header><i>${isCorrectOption(q,i)?"○":"×"}</i><b>${i+1}. ${escapeQuestionText(q.choices[i])}</b>${selectionIndices(state.selected).includes(i)?"<span>あなたの回答</span>":""}</header><p>${escapeQuestionText(n)||(isCorrectOption(q,i)?"公式正答に含まれる選択肢です。":"公式正答に含まれない選択肢です。")}</p></article>`).join("")+explanationReferences(q);el.detailBox.querySelector("summary").textContent=q.hasExplanation?"選択肢ごとの解説":"公式正答の確認（解説は準備中）";el.detailBox.open=true;el.submit.hidden=true;el.next.hidden=false;el.streak.textContent=state.streak;status();if(!ok&&e.disease){el.avatarStage.classList.add("danger-flash");setTimeout(()=>el.avatarStage.classList.remove("danger-flash"),1400)}el.next.textContent=mistakeLimitReached()?"結果を見る →":"次の問題へ →"}
function status(){el.healthValue.textContent=state.health;el.healthBar.style.width=`${state.health}%`;el.healthBar.style.background=state.health<40?"#d94b4b":state.health<70?"#d98a32":"#69d5c1";el.spo2.textContent=state.spo2;el.pulse.textContent=state.pulse;el.focus.textContent=state.focus;projectionStatus()}
function records(){el.recordCount.textContent=`${state.records.length}件`;el.recordLog.innerHTML=state.records.map(r=>`<article class="record-item ${r.ok?"":"wrong-record"}"><small>CASE ${String(r.caseNo).padStart(2,"0")} · ${r.ok?"適切":"誤った判断"}</small><p>${r.quote}</p><b>${r.result}</b></article>`).join("")}
function effectTitle(e){return e.kind==='disease'?`${e.name}を発症しました`:`${e.name}を体験しています`}
function avatar(e){
const episodes=state.anatomyEpisodes||[],latest=episodes.at(-1),classes=[...new Set(episodes.flatMap(item=>item.avatarClasses.split(' ')))];
el.avatarStage.className=['avatar-stage',...classes].join(' ');
el.avatarState.textContent=latest?'体験中':'STABLE';
el.avatarCallout.innerHTML=latest?`<b>${escapeQuestionText(effectTitle(latest))}</b><span>${escapeQuestionText(latest.detail)}</span>`:'<b>正常</b><span>症状はありません</span>';
el.symptomChips.innerHTML=episodes.length?[...new Set(episodes.map(item=>item.name))].map(name=>`<span>${escapeQuestionText(name)}</span>`).join(''):'<span class="empty-chip">状態異常なし</span>';
let panel=$('#diseaseEpisodes');if(panel)panel.innerHTML=[...new Map(episodes.map(item=>[item.name,item])).values()].reverse().map(item=>`<article><b>${escapeQuestionText(item.name)}</b><p>${escapeQuestionText(item.detail)}</p></article>`).join('');
if(e?.disease){el.feedbackLabel.textContent="PATHOLOGY TRANSFER";el.feedbackTitle.textContent=effectTitle(e);el.consequence.textContent=`${e.detail} ミス ${state.review.length} / ${mistakeLimit()}回`;}
projectionVisual(e);
}

function next(){if(mistakeLimitReached()){death();return}state.index<QUESTION_BANK.length-1?(state.index++,render()):finish()}
function finish(){$("#finalScore").textContent=state.score;$("#finalHealth").textContent=state.health;$("#reviewCount").textContent=state.review.length;$("#resultMessage").textContent=state.score>=8?"病態の連鎖を断ち切りました。":state.score>=5?"夜勤完了。誤答症例を確認しましょう。":"症状が蓄積しました。再挑戦しましょう。";el.modal.hidden=false;save()}
function death(){$("#resultCard").classList.add("death");$("#resultEyebrow").textContent="IDENTITY LOST";$("#resultTitle").textContent="自分に戻れなくなった";$("#finalScore").textContent=state.score;$("#finalHealth").textContent=0;$("#reviewCount").textContent=state.review.length;$("#resultMessage").textContent="投影から抜け出せず、今回の夜勤は終了です。解説を振り返り、次の夜勤へ。";el.modal.hidden=false;save()}
function save(){localStorage.setItem("recare-last",JSON.stringify({score:state.score,review:state.review,records:state.records,date:new Date().toISOString()}))}
function reset(){Object.assign(state,fresh());el.modal.hidden=true;$("#resultCard").classList.remove("death");$("#resultEyebrow").textContent="SHIFT COMPLETE";$("#resultTitle").textContent="夜勤終了";el.recordLog.innerHTML='<p class="empty-record">判断すると、選んだ発言と身体に起きたことがここに記録されます。</p>';el.recordCount.textContent="0件";render()}
function openReport(){let q=QUESTION_BANK[state.index];$("#reportQuestion").textContent=`${q.source}｜${q.question}`;$("#reportMessage").value="";$("#reportStatus").textContent="";$("#reportModal").hidden=false}
function closeReport(){$("#reportModal").hidden=true}
function sendReport(event){event.preventDefault();let q=QUESTION_BANK[state.index],report={reportedAt:new Date().toISOString(),questionId:q.id,source:q.source,question:q.question,selectedAnswer:state.selected===null?"未回答":formatSelection(q,state.selected),officialAnswer:formatCorrectAnswers(q),explanation:q.explanation,type:$("#reportType").value,message:$("#reportMessage").value.trim(),replyTo:$("#reportReply").value.trim()},saved=JSON.parse(localStorage.getItem("recare-feedback")||"[]");saved.push(report);localStorage.setItem("recare-feedback",JSON.stringify(saved));let recipient=window.RECARE_CONFIG?.feedbackEmail||"",subject=encodeURIComponent(`[RE:CARE 誤り報告] ${q.id} ${report.type}`),body=encodeURIComponent(`問題: ${report.questionId}\n出典: ${report.source}\n種別: ${report.type}\n報告: ${report.message}\n選択回答: ${report.selectedAnswer}\n正答表示: ${report.officialAnswer}\n現在の解説: ${report.explanation}\n返信先: ${report.replyTo||"なし"}\n報告日時: ${report.reportedAt}`);if(recipient){$("#reportStatus").textContent="メール作成画面を開きます。端末にも控えを保存しました。";location.href=`mailto:${encodeURIComponent(recipient)}?subject=${subject}&body=${body}`}else{$("#reportStatus").textContent="端末に報告を保存しました。管理者の受信用メールは設定待ちです。"}}
el.submit.onclick=submit;el.next.onclick=next;$("#resetButton").onclick=reset;$("#retryButton").onclick=reset;$("#reportButton").onclick=openReport;$("#reportClose").onclick=closeReport;$("#reportForm").onsubmit=sendReport;$("#reportModal").onclick=e=>{if(e.target.id==="reportModal")closeReport()};$("#soundButton").onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==="◌"?"●":"◌";document.addEventListener("keydown",e=>{if(e.target.closest("input,textarea,select")||!$("#titleScreen").hidden||document.querySelector(".mypage:not([hidden]),.auth-gate:not([hidden])"))return;if(e.key==="Escape")closeReport();if(e.key>="1"&&e.key<="5")select(+e.key-1);if(e.key==="Enter"&&!$("#reportModal").hidden)return;if(e.key==="Enter")state.answered?next():submit()});render();
