const baseSubmit=submit,baseDeath=death;
submit=function(){if(!canSubmitAnswer(QUESTION_BANK[state.index],state.selected)||state.answered)return;let q=QUESTION_BANK[state.index],correct=isCorrectAnswer(q,state.selected);baseSubmit();sound(correct?"ok":"wrong");};
death=function(){sound("death");$("#finalTotal").textContent=QUESTION_BANK.length;$("#reviewButton").hidden=!state.review.length;baseDeath();$("#resultEyebrow").textContent="IDENTITY LOST";$("#resultTitle").textContent="自分に戻れなくなった";$("#resultMessage").textContent=`患者への投影から抜け出せず、今回の夜勤は終了です。全${QUESTION_BANK.length}問中${state.review.length}回のミス（2割・端数切り上げ）。記録を振り返り、もう一度、自分の判断を取り戻しましょう。`};
finish=function(){let ratio=state.score/QUESTION_BANK.length;$("#finalScore").textContent=state.score;$("#finalTotal").textContent=QUESTION_BANK.length;$("#finalHealth").textContent=state.health;$("#reviewCount").textContent=state.review.length;$("#reviewButton").hidden=!state.review.length;$("#resultMessage").textContent=ratio>=.8?"自分を見失わず、夜勤を終えました。残った投影は、復習で振り返りましょう。":ratio>=.5?"夜勤完了。誤答症例を確認しましょう。":"症状が蓄積しました。間違いだけ復習して立て直しましょう。";$("#resultTitle").textContent="自分のままで、夜勤終了";el.modal.hidden=false;save()};
function startReview(){let ids=new Set(state.review),missed=fullBank.filter(q=>ids.has(q.id));if(!missed.length)return;QUESTION_BANK=shuffle(missed);reset();$("#resultEyebrow").textContent="REVIEW SHIFT";$("#finalTotal").textContent=QUESTION_BANK.length}
function startFull(){QUESTION_BANK=shuffle([...fullBank]).slice(0,20);reset();$("#finalTotal").textContent=QUESTION_BANK.length}
el.submit.onclick=submit;$("#reviewButton").onclick=startReview;$("#retryButton").onclick=startFull;
$("#soundButton").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?"♪":"♪×";e.currentTarget.classList.toggle("sound-on",soundOn);e.currentTarget.setAttribute("aria-label",soundOn?"サウンドをオフにする":"サウンドをオンにする");if(soundOn)tone(660,.12)};
QUESTION_BANK=shuffle([...fullBank]).slice(0,20);$("#finalTotal").textContent=QUESTION_BANK.length;render();

function showTitle(){el.modal.hidden=true;$("#gameShell").classList.add("game-hidden");$("#titleScreen").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
function beginShift(){startFull();$("#titleScreen").hidden=true;$("#gameShell").classList.remove("game-hidden");window.scrollTo({top:0,behavior:"smooth"})}
$("#startGame").onclick=beginShift;$("#howButton").onclick=()=>$("#howPanel").hidden=false;$("#howClose").onclick=()=>$("#howPanel").hidden=true;$("#howPanel").onclick=e=>e.stopPropagation();$(".brand").onclick=e=>{e.preventDefault();showTitle()};
const prior=JSON.parse(localStorage.getItem("recare-last")||"null");if(prior){let date=new Date(prior.date).toLocaleDateString("ja-JP"),total=prior.records?.length||20;$("#lastResult").innerHTML=`<span>LAST RECORD</span><b>${date} · ${prior.score}/${total}正解 · 要復習${prior.review?.length||0}</b>`}

async function submitReportDirect(event){event.preventDefault();let button=event.currentTarget.querySelector("button[type=submit]"),q=QUESTION_BANK[state.index],recipient=window.RECARE_CONFIG?.feedbackEmail,report={reportedAt:new Date().toISOString(),questionId:q.id,source:q.source,question:q.question,type:$("#reportType").value,message:$("#reportMessage").value.trim(),selectedAnswer:state.selected===null?"未回答":formatSelection(q,state.selected),displayedAnswer:formatCorrectAnswers(q),explanation:q.explanation,replyTo:$("#reportReply").value.trim(),page:location.href};if(report.message.length<5)return;let saved=JSON.parse(localStorage.getItem("recare-feedback")||"[]");saved.push(report);localStorage.setItem("recare-feedback",JSON.stringify(saved));if(!recipient){$("#reportStatus").textContent="受信先が未設定です。端末に控えを保存しました。";return}button.disabled=true;button.textContent="送信中…";$("#reportStatus").textContent="報告を送信しています。";try{let response=await fetch(`https://formsubmit.co/ajax/${recipient}`,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({_subject:`[RE:CARE 誤り報告] ${report.questionId} ${report.type}`,name:"RE:CARE Error Report",email:report.replyTo||recipient,問題ID:report.questionId,出典:report.source,問題文:report.question,報告種別:report.type,報告内容:report.message,選択回答:report.selectedAnswer,表示中の正答:report.displayedAnswer,表示中の解説:report.explanation,報告日時:report.reportedAt,ページ:report.page})});let result=await response.json();if(!response.ok||result.success===false)throw new Error(result.message||"送信に失敗しました");$("#reportStatus").textContent="報告を送信しました。ご協力ありがとうございます。";button.textContent="送信済み ✓";setTimeout(closeReport,1600)}catch(error){$("#reportStatus").textContent="送信できませんでした。控えは端末に保存されています。通信後にもう一度お試しください。";button.disabled=false;button.textContent="再送する →"}}
$("#reportForm").onsubmit=submitReportDirect;
