(()=>{
const ACTIVE="recare-active-user",USERS="recare-local-accounts",active=localStorage.getItem(ACTIVE);if(!active)return;
const isAdmin=active==="test";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),profileKey=u=>`recare-profile-v1:${u}`;
const read=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}},profile=()=>{const p=read(profileKey(localStorage.getItem(ACTIVE)),{}),bank=new Map((fullBank.concat(window.ORIGINAL_BANK||[])).map(q=>[q.id,q]));return {...p,history:(p.history||[]).filter(h=>bank.has(h.id)).map(h=>({...h,category:bank.get(h.id).category})),stats:Object.fromEntries(Object.entries(p.stats||{}).filter(([id])=>bank.has(id)))}},users=()=>read(USERS,{});
async function localHash(key,pin){let data=new TextEncoder().encode(`RECARE:${key}:${pin}:LOCAL`),digest=await crypto.subtle.digest("SHA-256",data);return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function currentName(){let key=localStorage.getItem(ACTIVE);return users()[key]?.name||key}
function inject(){document.body.insertAdjacentHTML("beforeend",`<section class="mypage" id="mypage" hidden><div class="mypage-shell"><aside class="mypage-side"><h2>RE:CARE</h2><div class="mypage-identity"><div class="mypage-avatar" id="mypageAvatar"></div><div><b id="mypageName"></b><small>${isAdmin?"ADMINISTRATOR":window.RECARE_CLOUD?.enabled()?"CLOUD PROFILE":"LOCAL PROFILE"}</small></div></div><nav class="mypage-nav"><button class="active" data-page="summary">成績</button><button data-page="ranking">ランキング</button><button data-page="history">回答履歴</button>${isAdmin?'<button class="admin-nav" data-page="admin">管理者</button>':""}<button data-page="account">アカウント</button></nav><button class="mypage-logout" id="mypageLogout">ログアウト</button></aside><main class="mypage-main"><button class="mypage-close" id="mypageClose">×</button><section class="mypage-panel" data-panel="summary"></section><section class="mypage-panel" data-panel="ranking" hidden></section><section class="mypage-panel" data-panel="history" hidden></section>${isAdmin?'<section class="mypage-panel" data-panel="admin" hidden></section>':""}<section class="mypage-panel" data-panel="account" hidden></section></main></div></section>`);$("#accountMenuButton")?.addEventListener("click",open);document.querySelector(".title-actions")?.insertAdjacentHTML("afterend",`<div class="title-account-actions"><button class="title-ranking-btn" id="titleMyPageButton" type="button">マイページ →</button><button class="title-ranking-btn" id="titleRankingButton" type="button">LEADERBOARD →</button></div>`);$("#titleMyPageButton")?.addEventListener("click",open);$("#titleRankingButton")?.addEventListener("click",()=>{open();show("ranking")});$("#mypageClose").onclick=close;$("#mypage").addEventListener("click",e=>{if(e.target.id==="mypage")close()});document.querySelectorAll(".mypage-nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));$("#mypageLogout").onclick=logout}
function renderIdentity(){let name=currentName();$("#mypageName").textContent=name;$("#mypageAvatar").textContent=name.slice(0,1).toUpperCase()}
function renderSummary(){let p=profile(),rate=p.answered?Math.round((p.correct||0)/p.answered*100):0,level=Math.floor((p.xp||0)/250)+1,rows={};for(const h of p.history||[]){let r=rows[h.category]??={ok:0,total:0};r.total++;if(h.correct)r.ok++}let bars=Object.entries(rows).sort((a,b)=>b[1].total-a[1].total).map(([name,r])=>{let n=Math.round(r.ok/r.total*100);return`<div class="category-score"><span>${esc(name)}</span><div><i style="width:${n}%"></i></div><b>${n}%</b></div>`}).join("")||'<p class="history-empty">回答すると領域別成績が表示されます。</p>';document.querySelector('[data-panel="summary"]').innerHTML=`<p class="mypage-kicker">PERFORMANCE</p><h3>学習ダッシュボード</h3><div class="profile-metrics"><div class="profile-metric"><span>LEVEL</span><b>${level}</b></div><div class="profile-metric"><span>XP</span><b>${p.xp||0}</b></div><div class="profile-metric"><span>ACCURACY</span><b>${rate}%</b></div><div class="profile-metric"><span>MASTERED</span><b>${Object.values(p.stats||{}).filter(s=>s.seen&&s.correct/s.seen>=.8).length}</b></div></div><div class="category-summary"><h4>領域別パフォーマンス</h4>${bars}</div>`}
function historyQuestionText(h){const q=(fullBank.concat(window.ORIGINAL_BANK||[])).find(q=>q.id===h.id);return q?questionTextForDisplay(q):h.question}
function renderHistory(){let list=(profile().history||[]).map(h=>`<article class="history-entry ${h.correct?"ok":""}"><i>${h.correct?"✓":"!"}</i><div><b>${esc(historyQuestionText(h))}</b><small>${esc(h.category)}｜回答：${esc(h.selected)}${h.correct?"":`｜正答：${esc(h.correctAnswer)}`}</small></div><time>${new Date(h.at).toLocaleString("ja-JP")}</time></article>`).join("")||'<div class="history-empty">新しいバージョンで回答した履歴がここに表示されます。</div>';document.querySelector('[data-panel="history"]').innerHTML=`<p class="mypage-kicker">ACTIVITY</p><h3>回答履歴</h3><div class="history-toolbar"><span>直近200件</span><span>${(profile().history||[]).length}件</span></div><div class="history-list">${list}</div>`}
function localRanking(){let p=profile(),answered=p.answered||0,correct=p.correct||0,xp=p.xp||0;return[{rank:1,username:localStorage.getItem(ACTIVE),display_name:currentName(),xp,answered,correct,accuracy:answered?Math.round(correct/answered*100):0,level:Math.floor(xp/250)+1}]}
let rankingRequest=0;
async function renderRanking(){
  const panel=document.querySelector('[data-panel="ranking"]'),cloud=window.RECARE_CLOUD?.enabled(),activeKey=localStorage.getItem(ACTIVE);
  panel.innerHTML='<p class="mypage-kicker">LEADERBOARD</p><h3>ランキング</h3><div class="ranking-tabs"><button type="button" class="active" data-rank="general" aria-pressed="true">総合</button><button type="button" data-rank="daily" aria-pressed="false">デイリー</button><button type="button" data-rank="required" aria-pressed="false">必修</button></div><p class="ranking-rule" id="rankingRule"></p><div id="rankingPersonal"></div><div class="ranking-list" id="rankingList" aria-live="polite"></div>';
  const rules={general:'累計XP順。同点の場合は正解数順です。',daily:'今日の1問を連続達成した日数で競います。その日の初回回答で記録します。',required:'必修モードの正答率で競います。同率なら回答数順です。'};
  async function loadRank(kind){
    const request=++rankingRequest,list=panel.querySelector('#rankingList'),personal=panel.querySelector('#rankingPersonal'),p=profile();
    panel.querySelector('#rankingRule').textContent=rules[kind];
    personal.replaceChildren();
    if(kind!=='general'){
      const answered=p.requiredAnswered||0,score=kind==='daily'?(p.dailyStreak||0):answered?Math.round((p.requiredCorrect||0)/answered*100):0;
      personal.innerHTML='<div class="ranking-personal"><b>あなたの記録</b><strong>'+score+(kind==='daily'?'日':'%')+'</strong><span>'+(kind==='daily'?(p.dailyLastDate?'最終挑戦：'+esc(p.dailyLastDate):'まだ挑戦していません'):answered+'問回答・'+(p.requiredCorrect||0)+'問正解')+'</span><button type="button" class="secondary-btn" id="rankingPlay">'+(kind==='daily'?'今日の1問に挑戦':'必修問題に挑戦')+'</button><small>この端末に保存された記録です。全体順位は下の一覧に表示します。</small></div>';
      personal.querySelector('#rankingPlay').onclick=()=>{
        close();showTitle();
        if(kind==='daily')document.querySelector('#startDailyChallenge').click();
        else{const source=document.querySelector('input[name="questionSource"][value="past"]');if(source){source.checked=true;source.dispatchEvent(new Event('change',{bubbles:true}))}const category=document.querySelector('#premiumCategory');category.value='required';category.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#startGame').click()}
      };
    }
    list.innerHTML='<div class="ranking-loading">成績を集計しています…</div>';
    if(!cloud){list.innerHTML=kind==='general'?renderRows(localRanking(),kind):'<div class="history-empty">全体ランキングはクラウド接続時に表示されます。</div>';return}
    try{
      const rows=kind==='general'?await window.RECARE_CLOUD.leaderboard(50):await window.RECARE_CLOUD.challengeLeaderboard(kind,50);
      if(request!==rankingRequest||!list.isConnected)return;
      list.innerHTML=rows?.length?renderRows(rows,kind):'<div class="history-empty">'+(kind==='general'?'まだランキング対象の記録がありません。':'まだランキング対象の記録がありません。'+(kind==='daily'?'今日の1問に正解':'必修問題に正解')+'すると、同期後に掲載されます。')+'</div>';
    }catch(error){
      if(request!==rankingRequest||!list.isConnected)return;
      list.innerHTML='<div class="ranking-notice"><b>ランキングを取得できませんでした</b><span>しばらくしてから、もう一度お試しください。</span><button type="button" class="secondary-btn" id="rankingRetry">再読み込み</button></div>';
      list.querySelector('#rankingRetry').onclick=()=>loadRank(kind);
    }
  }
  function renderRows(rows,kind){return rows.map(r=>{
    const rank=Number(r.rank),badge=rank<=3&&rank>=1?['🥇','🥈','🥉'][rank-1]:'#'+rank;
    const cells=kind==='general'?'<span><small>LEVEL</small><b>'+esc(r.level)+'</b></span><span><small>XP</small><b>'+esc(r.xp)+'</b></span><span><small>正答率</small><b>'+esc(r.accuracy)+'%</b></span><span><small>回答</small><b>'+esc(r.answered)+'</b></span>':'<span class="challenge-score"><small>'+(kind==='daily'?'連続達成':'正答率')+'</small><b>'+esc(r.score)+(kind==='required'?'%':'日')+'</b></span>'+(kind==='required'?'<span><small>回答</small><b>'+esc(r.detail)+'</b></span>':'');
    return '<div class="ranking-row '+(r.username===activeKey?'is-me':'')+'"><b class="ranking-rank">'+badge+'</b><span class="ranking-name">'+esc(r.display_name||r.username)+(r.username===activeKey?'<small>YOU</small>':'')+'</span>'+cells+'</div>';
  }).join('')}
  panel.querySelectorAll('[data-rank]').forEach(b=>b.onclick=()=>{panel.querySelectorAll('[data-rank]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});loadRank(b.dataset.rank)});
  loadRank('general');
}
function renderAccount(){let name=currentName();document.querySelector('[data-panel="account"]').innerHTML=`<p class="mypage-kicker">ACCOUNT</p><h3>アカウント設定</h3><form class="account-form" id="accountForm"><label>ユーザーネーム<input id="newUsername" required minlength="2" maxlength="20" value="${esc(name)}"></label><label>新しい4桁コード（変更しない場合は空欄）<input id="newPin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="••••"></label><button class="primary-btn" type="submit">変更を保存</button><p class="account-status" id="accountStatus"></p></form><div class="danger-zone"><h4>退会</h4><p>クラウド上のアカウント、成績、回答履歴を完全に削除します。この操作は元に戻せません。</p><button id="deleteStart">退会手続き</button><div class="delete-confirm" id="deleteConfirm" hidden><label>確認のため「${esc(name)}」と入力<input id="deleteName"></label><button id="deleteAccount">完全に削除する</button><p class="account-status" id="deleteStatus"></p></div></div>`;$("#accountForm").onsubmit=updateAccount;$("#deleteStart").onclick=()=>$("#deleteConfirm").hidden=false;$("#deleteAccount").onclick=deleteAccount}
function questionRows(term=""){let key=term.toLowerCase(),bank=fullBank;return bank.filter(q=>!key||`${q.id} ${q.category} ${q.question}`.toLowerCase().includes(key)).slice(0,200).map(q=>`<article class="admin-question"><header><b>${esc(q.id)}</b><span>${esc(q.category)}</span></header><p>${esc(questionTextForDisplay(q))}</p><ol>${q.choices.map((c,i)=>`<li class="${isCorrectOption(q,i)?"answer":""}">${esc(choiceTextForDisplay(q,i))}${isCorrectOption(q,i)?" <b>✓ 正解</b>":""}</li>`).join("")}</ol><small>${esc(q.explanation)}</small></article>`).join("")||'<div class="history-empty">該当する問題はありません。</div>'}
async function renderAdmin(){if(!isAdmin)return;let panel=document.querySelector('[data-panel="admin"]');panel.innerHTML='<p class="mypage-kicker">ADMIN CONSOLE</p><h3>管理者ダッシュボード</h3><div class="ranking-loading">権限と回答記録を確認しています…</div>';let data={users:[],answers:[]};try{if(window.RECARE_CLOUD?.enabled()){let cloudUser=window.RECARE_CLOUD.session()?.username;if(cloudUser!=="test")throw new Error(`クラウド側は「${cloudUser||"未ログイン"}」でログイン中です。testでログインし直してください。`);data=await window.RECARE_CLOUD.adminDashboard()}else data={users:[{displayName:currentName(),username:active,xp:profile().xp||0,answered:profile().answered||0,correct:profile().correct||0}],answers:profile().history||[]}}catch(error){panel.innerHTML=`<p class="mypage-kicker">ADMIN CONSOLE</p><h3>管理者ダッシュボード</h3><div class="ranking-notice"><b>管理者データを取得できません</b><span>${esc(error.message||"不明なエラー")}</span><span>admin-setup.sql を再実行し、testでログアウト→再ログインしてください。</span></div>`;return}let users=(data.users||[]).map(u=>{let total=+u.answered||0,ok=+u.correct||0;return`<tr><td>${esc(u.displayName||u.username)}</td><td>${u.xp||0}</td><td>${total}</td><td>${total?Math.round(ok/total*100):0}%</td></tr>`}).join(""),answers=(data.answers||[]).filter(h=>(fullBank.concat(window.ORIGINAL_BANK||[])).some(q=>q.id===h.id)).map(h=>`<article class="admin-answer ${h.correct?"ok":"ng"}"><i>${h.correct?"✓":"×"}</i><div><b>${esc(h.displayName||h.username||currentName())}</b><span>${esc(historyQuestionText(h))}</span><small>回答：${esc(h.selected)}｜正解：${esc(h.correctAnswer)}</small></div></article>`).join("")||'<div class="history-empty">回答履歴はありません。</div>';panel.innerHTML=`<p class="mypage-kicker">ADMIN CONSOLE · TEST ONLY</p><h3>管理者ダッシュボード</h3><div class="admin-tabs"><button class="active" data-admin-view="activity">ユーザー回答</button><button data-admin-view="questions">問題・正答</button></div><section class="admin-view" data-admin-panel="activity"><table class="admin-users"><thead><tr><th>ユーザー</th><th>XP</th><th>回答</th><th>正答率</th></tr></thead><tbody>${users}</tbody></table><h4>直近の正解・不正解</h4><div class="admin-answers">${answers}</div></section><section class="admin-view" data-admin-panel="questions" hidden><input class="admin-search" id="adminQuestionSearch" placeholder="問題番号・分類・問題文を検索"><p class="ranking-rule">全${(fullBank.concat(window.ORIGINAL_BANK||[])).length}問。検索結果は先頭200件まで表示します。</p><div class="admin-questions">${questionRows()}</div></section>`;panel.querySelectorAll("[data-admin-view]").forEach(b=>b.onclick=()=>{panel.querySelectorAll("[data-admin-view]").forEach(x=>x.classList.toggle("active",x===b));panel.querySelectorAll("[data-admin-panel]").forEach(x=>x.hidden=x.dataset.adminPanel!==b.dataset.adminView)});$("#adminQuestionSearch").oninput=e=>panel.querySelector(".admin-questions").innerHTML=questionRows(e.target.value)}
function show(page){document.querySelectorAll(".mypage-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));document.querySelectorAll(".mypage-panel").forEach(p=>p.hidden=p.dataset.panel!==page);if(page==="summary")renderSummary();if(page==="ranking")renderRanking();if(page==="history")renderHistory();if(page==="admin")renderAdmin();if(page==="account")renderAccount()}
function open(){renderIdentity();show("summary");$("#mypage").hidden=false;document.body.style.overflow="hidden"}function close(){$("#mypage").hidden=true;document.body.style.overflow=""}
function logout(){window.RECARE_CLOUD?.logout();localStorage.removeItem(ACTIVE);location.reload()}
async function updateAccount(e){e.preventDefault();let old=localStorage.getItem(ACTIVE),display=$("#newUsername").value.trim(),next=display.toLowerCase(),pin=$("#newPin").value,status=$("#accountStatus");if(!/^[\p{L}\p{N}_-]{2,20}$/u.test(display)){status.textContent="使用できないユーザーネームです。";return}if(pin&&!/^\d{4}$/.test(pin)){status.textContent="コードは4桁の数字で入力してください。";return}status.textContent="変更しています…";try{let db=users();if(db[next]&&next!==old)throw new Error("そのユーザーネームは使用されています");if(window.RECARE_CLOUD?.enabled())await window.RECARE_CLOUD.updateAccount(next,pin);let entry=db[old]||{name:display};delete db[old];entry.name=display;if(pin)entry.hash=await localHash(next,pin);db[next]=entry;localStorage.setItem(USERS,JSON.stringify(db));if(next!==old){localStorage.setItem(profileKey(next),localStorage.getItem(profileKey(old))||"{}");localStorage.removeItem(profileKey(old))}localStorage.setItem(ACTIVE,next);status.textContent="変更しました。";setTimeout(()=>location.reload(),600)}catch(error){status.textContent=error.message}}
async function deleteAccount(){let key=localStorage.getItem(ACTIVE),status=$("#deleteStatus");if($("#deleteName").value.trim().toLowerCase()!==key){status.textContent="ユーザーネームが一致しません。";return}status.textContent="削除しています…";try{if(window.RECARE_CLOUD?.enabled())await window.RECARE_CLOUD.deleteAccount();let db=users();delete db[key];localStorage.setItem(USERS,JSON.stringify(db));localStorage.removeItem(profileKey(key));localStorage.removeItem(ACTIVE);location.reload()}catch(error){status.textContent=error.message}}
inject();
})();
