"""Publish authored choice explanations only after an explicit review record exists."""
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DIR=ROOT/'data/additional-explanations'
def read(path):return json.loads(path.read_text(encoding='utf-8-sig'))
def write(path,value):path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def build():
    questions=read(ROOT/'data/additional_questions.json')
    by_id={q['id']:q for q in questions}
    reviews=read(DIR/'reviews.json') if (DIR/'reviews.json').exists() else {}
    # Independently reviewed batches keep their own records; never overwrite a decision.
    for review_path in sorted(DIR.glob('reviews-*.json')):
        batch_reviews=read(review_path)
        overlap=reviews.keys() & batch_reviews.keys()
        assert not overlap, f'Duplicate review IDs in {review_path.name}: {sorted(overlap)}'
        reviews.update(batch_reviews)
    anchors=read(DIR/'input-anchors.json')
    drafts={}
    for path in sorted(DIR.glob('*.txt')):
        for line in path.read_text(encoding='utf-8-sig').splitlines():
            if not line.strip():continue
            identifier,*notes=line.split('|')
            assert identifier in by_id and identifier not in drafts,identifier
            assert len(notes)==len(by_id[identifier]['choices']),identifier
            assert all(0<len(t)<=200 for t in notes),identifier
            drafts[identifier]=notes
    assert not (reviews.keys()-drafts.keys()), f'Review without draft: {sorted(reviews.keys()-drafts.keys())}'
    published=[];output=[]
    for identifier,notes in drafts.items():
        q=by_id[identifier]
        anchor={k:q.get(k) for k in anchors['fields']}
        digest=hashlib.sha256(json.dumps(anchor,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
        assert digest==anchors['sha256_by_id'][identifier],identifier
        review=reviews.get(identifier)
        if not review:continue
        assert review['status'] in ('PASS','VERIFIED','FIXED','UNKNOWN','REJECT')
        assert len(review['checks'])==3 and all(isinstance(c,bool) for c in review['checks']),identifier
        if review['status'] in ('PASS','VERIFIED','FIXED'):
            assert all(review['checks']),identifier
        else:assert review.get('review_reason'),identifier
        ce=[{'choice':i+1,'correct':i+1 in q['correct_answers'],'title':c,'explanation':notes[i]} for i,c in enumerate(q['choices'])]
        result={'id':identifier,'choice_explanations':ce,'status':review['status'],'review_reason':review.get('review_reason',''),'fixes_made':review.get('fixes_made',[])}
        output.append(result)
        if result['status']!='REJECT':published.append({'id':identifier,'record':result,'input_anchor':anchor,'sources':review.get('sources',[])})
    write(ROOT/'data/additional_choice_explanations.json',output)
    report={'input':len(questions),'drafted':len(drafts),'processed':len(output),**{s:sum(r['status']==s for r in output) for s in ('PASS','VERIFIED','FIXED','UNKNOWN','REJECT')},'missing':len(by_id.keys()-{r['id'] for r in output})}
    report['by_exam']={str(exam):{
        'input':sum(q['exam']==exam for q in questions),
        'drafted':sum(identifier.startswith(f'{exam}-') for identifier in drafts),
        'processed':sum(r['id'].startswith(f'{exam}-') for r in output),
        'unknown':sum(r['id'].startswith(f'{exam}-') and r['status']=='UNKNOWN' for r in output)
    } for exam in sorted({q['exam'] for q in questions})}
    write(ROOT/'data/additional_choice_explanation_report.json',report)
    (ROOT/'additional-explanations.js').write_text('// Generated by scripts/build_additional_explanations.py.\nwindow.RECARE_EXPLANATIONS=(window.RECARE_EXPLANATIONS||[]).concat('+json.dumps(published,ensure_ascii=False,separators=(',',':'))+');\n',encoding='utf-8')
    print(json.dumps(report))
if __name__=='__main__':build()
