"""Build the server's authoritative, zero-based answer catalog without editing inputs."""
import hashlib
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUTS = ('data/questions.json', 'data/additional_questions.json')


def build():
    rows = []
    identifiers = set()
    by_exam = Counter()
    for filename in INPUTS:
        questions = json.loads((ROOT / filename).read_text(encoding='utf-8-sig'))
        for question in questions:
            identifier = question['id']
            if not isinstance(identifier, str) or not re.fullmatch(r'\d{3}-(?:AM|PM)-\d{3}', identifier):
                raise ValueError(f'Invalid question ID: {identifier!r}')
            if identifier in identifiers:
                raise ValueError(f'Duplicate question ID: {identifier}')
            if question.get('excluded'):
                raise ValueError(f'Excluded question in adopted catalog: {identifier}')
            identifiers.add(identifier)
            choices = question['choices']
            if not isinstance(choices, list) or not 2 <= len(choices) <= 10:
                raise ValueError(f'Invalid choices: {identifier}')
            if any(not isinstance(choice, str) or not choice.strip() for choice in choices):
                raise ValueError(f'Empty choice: {identifier}')
            if question['choice_numbers'] != list(range(1, len(choices) + 1)):
                raise ValueError(f'Nonsequential choice numbers: {identifier}')
            accepted = question['accepted_answer_sets']
            if not isinstance(accepted, list) or not accepted:
                raise ValueError(f'Missing accepted answers: {identifier}')
            normalized = set()
            for answer in accepted:
                if not isinstance(answer, list) or not answer:
                    raise ValueError(f'Empty accepted answer: {identifier}')
                if any(type(value) is not int or not 1 <= value <= len(choices) for value in answer):
                    raise ValueError(f'Invalid answer index: {identifier}')
                if len(set(answer)) != len(answer):
                    raise ValueError(f'Duplicate answer index: {identifier}')
                normalized.add(tuple(sorted(value - 1 for value in answer)))
            primary = question['correct_answers']
            if not isinstance(primary, list) or not primary or any(
                    type(value) is not int or not 1 <= value <= len(choices) for value in primary):
                raise ValueError(f'Invalid primary answer: {identifier}')
            # For questions accepting either choice, correct_answers contains their union.
            if {value - 1 for value in primary} != {value for answer in normalized for value in answer}:
                raise ValueError(f'Primary answer differs from accepted choice union: {identifier}')
            rows.append({'id': identifier, 'choice_count': len(choices),
                         'answer_sets': [list(answer) for answer in sorted(normalized)]})
            by_exam[str(question['exam'])] += 1
    rows.sort(key=lambda row: row['id'])
    if len(rows) != 1125:
        raise ValueError(f'Expected 1125 adopted questions, found {len(rows)}')
    serialized = json.dumps(rows, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    version = hashlib.sha256(serialized.encode('utf-8')).hexdigest()
    values = [f"  ('{row['id']}', {row['choice_count']}, '{json.dumps(row['answer_sets'], separators=(',', ':'))}'::jsonb)"
              for row in rows]
    sql = (
        '-- Generated by scripts/build_battle_catalog.py; do not edit manually.\n'
        '-- Apply after the battle schema. Answers use zero-based choice indices.\n'
        f'-- Catalog SHA-256: {version}\n'
        'BEGIN;\n'
        'INSERT INTO public.recare_battle_questions (id, choice_count, answer_sets) VALUES\n'
        + ',\n'.join(values)
        + '\nON CONFLICT (id) DO UPDATE SET\n'
          '  choice_count = EXCLUDED.choice_count,\n'
          '  answer_sets = EXCLUDED.answer_sets;\n'
          'COMMIT;\n'
    )
    destination = ROOT / 'setup/battle-question-seed.sql'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(sql, encoding='utf-8')
    schema = (ROOT / 'setup/battle-setup.sql').read_text(encoding='utf-8')
    seed_body = '\n'.join(line for line in sql.splitlines() if line not in ('BEGIN;', 'COMMIT;'))
    (ROOT / 'setup/battle-install.sql').write_text(
        '-- RE:CARE friend battle installation. Requires existing account schema.\n'
        'BEGIN;\n' + schema + '\n' + seed_body + '\n'
        "NOTIFY pgrst, 'reload schema';\nCOMMIT;\n", encoding='utf-8')
    report = {
        'catalog_version': version,
        'hash_algorithm': 'sha256',
        'hash_input': 'Question rows sorted by ID; UTF-8 JSON with sorted keys and compact separators',
        'answer_index_base': 0,
        'questions': len(rows),
        'by_exam': dict(sorted(by_exam.items())),
        'questions_with_alternate_answer_sets': sum(len(row['answer_sets']) > 1 for row in rows),
        'input_files': list(INPUTS),
        'output_file': 'setup/battle-question-seed.sql',
    }
    (ROOT / 'data/battle-catalog-report.json').write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False))


if __name__ == '__main__':
    build()
