"""Build presentation text without modifying official questions, choices or answer keys."""
import json,re,html,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(name):return json.loads((ROOT/name).read_text(encoding='utf-8-sig'))
def build():
    qs=read('data/questions.json')+read('data/additional_questions.json')
    context_rules={}
    for name in ['data/display-contexts-111-112.json','data/display-contexts-113-115.json']:
        for key,value in read(name).items():
            assert key not in context_rules,key
            context_rules[key]=value
    annotation_lines=set(read('data/display-english-annotations.json'))
    replacements=read('data/display-text-replacements.json')['replacements']
    def clean(text,id_,origin_id=None):
        preserve_layout=False
        for rule in replacements:
            if (id_ in rule['ids'] or origin_id in rule['ids']) and rule['from'] in text:
                text=text.replace(rule['from'],rule['to'])
                preserve_layout=preserve_layout or rule.get('preserve_layout',False)
        text=html.unescape(text).replace('\u00a0',' ')
        lines=text.splitlines();glosses=[];kept=[]
        for line in lines:
            stripped=line.strip()
            if stripped in annotation_lines and len(lines)>1:
                glosses.append(stripped)
            else:kept.append(stripped)
        # PDF line wrapping is not a paragraph boundary. Keep sentences and observations separate.
        out=''
        for line in kept:
            if not line:
                if out and not out.endswith('\n\n'):out+='\n\n'
                continue
            if out and not out.endswith('\n'):
                if preserve_layout:out+='\n'
                elif out[-1] in '。！？：:' or re.match(r'^(来院時|入院時|検査所見|身体所見|バイタルサイン|血液検査|尿検査)',line):out+='\n'
                elif re.search(r'[A-Za-z0-9]$',out) and re.match(r'[A-Za-z0-9]',line):out+=' '
            out+=line
        for spaced in ['身 長','体 重','体 温','血 圧','赤 血 球','白 血 球']:
            out=out.replace(spaced,spaced.replace(' ',''))
        return out.strip(),list(dict.fromkeys(glosses))
    entries={};seen_contexts=set();with_context=with_glosses=0
    for q in qs:
        contexts=[];glosses=[]
        if q.get('case_text'):
            text,g=clean(q['case_text'],q['id']);contexts.append({'title':'共通の症例','text':text});glosses+=g
        for prior in q.get('preceding_context',[]):
            seen_contexts.add(prior['id']);rule=context_rules[prior['id']]
            assert rule['text']+rule['removed']==prior['question'],prior['id']
            text,g=clean(rule['text'],q['id'],prior['id'])
            if text:contexts.append({'title':'症例の経過','text':text});glosses+=g
        stem,g=clean(q['question'],q['id']);glosses+=g
        choices=[]
        for choice in q['choices']:
            text,g=clean(choice,q['id']);choices.append(text+(' （'+'; '.join(g)+'）' if g else ''))
        assert stem and all(choices),q['id']
        raw='\n\n'.join(filter(None,[q.get('case_text'),*[p['question'] for p in q.get('preceding_context',[])],q['question']]))
        entries[q['id']]={'input_text':raw,'input_choices':q['choices'],'context':contexts,'question':stem,'choices':choices,'annotations':list(dict.fromkeys(glosses))}
        with_context+=bool(contexts);with_glosses+=bool(glosses)
    assert seen_contexts==set(context_rules)
    (ROOT/'question-presentations.js').write_text('// Generated by scripts/build_question_presentations.py. Display only.\nwindow.RECARE_QUESTION_PRESENTATIONS='+json.dumps(entries,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
    report={'input':len(qs),'with_context':with_context,'with_english_annotations':with_glosses,'reviewed_preceding_contexts':len(seen_contexts),'source_hashes':{n:hashlib.sha256((ROOT/n).read_bytes()).hexdigest() for n in ['data/questions.json','data/additional_questions.json']}}
    (ROOT/'data/question-presentation-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps(report))
if __name__=='__main__':build()
