"""Export only reviewed, adopted official questions for synchronous browser loading."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
questions = json.loads((ROOT / 'data/questions.json').read_text(encoding='utf-8'))
assert questions and len({q['id'] for q in questions}) == len(questions)
for q in questions:
    assert q['dataset_status'] == 'adopted' and not q['needs_review'] and not q['requires_image']
    assert q['accepted_answer_sets'] and all(q['accepted_answer_sets'])
    assert all(1 <= n <= len(q['choices']) for group in q['accepted_answer_sets'] for n in group)
additional_path = ROOT / 'data/additional_questions.json'
if additional_path.exists():
    additional = json.loads(additional_path.read_text(encoding='utf-8'))
    for q in additional:
        assert q['publication_mode'] == 'official_answers_only'
        assert q['dataset_status'] == 'adopted_official_answers_only'
        assert q['text_check']['structure'] == 'passed' and q['text_check']['official_answer_rows'] == 'matched'
        assert not q['requires_image'] and q['special_status'] not in ('採点除外','条件付き採点除外')
        assert q['accepted_answer_sets'] and all(group and all(1 <= n <= len(q['choices']) for n in group) for group in q['accepted_answer_sets'])
    questions += additional
assert len({q['id'] for q in questions}) == len(questions)
from classification_schema import CATEGORIES
catalog = {'classification':'非公式の学習内容分類。必修はquestion_typeで管理。分類要確認の問題を含む。', 'categories':[]}
for category in CATEGORIES:
    subset = [q for q in questions if q.get('category') == category]
    catalog['categories'].append({'name':category, 'subcategories':[
        {'name':sub, 'topics':sorted({q['topic'] for q in subset if q['subcategory'] == sub})}
        for sub in sorted({q['subcategory'] for q in subset})]})
(ROOT / 'data/categories.json').write_text(json.dumps(catalog, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
(ROOT / 'official-questions.js').write_text('// Generated by scripts/export_game_questions.py; do not edit.\nwindow.OFFICIAL_QUESTIONS = ' + json.dumps(questions, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'Exported {len(questions)} official questions (additional years: answers-only publication)')
